name: 'Unity License Activation (XRTK)'
description: 'Runs Unity with the provided options'
branding:
  icon: 'at-sign'
  color: 'blue'
inputs:
  editor-path:
    description: 'Path to the Unity Editor'
    required: true
  project-path:
    description: 'Path to the Unity project'
    required: true
  license-type:
    description: 'License type to activate (professional or personal)'
    required: true
    default: 'personal'
runs:
  using: 'node16'
  main: 'index.js'
  post: 'post.js'
