name: 'Unity License Activation (XRTK)'
description: 'Runs Unity with the provided options'
branding:
  icon: 'at-sign'
  color: 'blue'
inputs:
  editor-path:
    description: 'Path to the Unity Editor'
    required: true
  project-path:
    description: 'Path to the Unity project'
    required: true
  license-type:
    description: 'License type to activate (professional or personal)'
    required: false
    default: 'Personal'
  username:
    description: 'Unity Username'
    required: true
    default: ''
  password:
    description: 'Unity Password'
    required: true
    default: ''
  license:
    description: '.ulf license file contents (Only used for Personal license type)'
    required: false
  serial:
    description: 'Unity Serial (Only used for Professional license type)'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
  post: 'post.js'
