name: validate

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# concurrency:
#   group: ${{ github.ref }}

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   build-target: StandaloneLinux64
          - os: windows-latest
            build-target: StandaloneWindows64
          - os: macos-latest
            build-target: StandaloneOSX
    steps:
      - name: checkout self
        uses: actions/checkout@v3

      - run: npm install

      - name: checkout test project
        uses: actions/checkout@v3
        with:
          repository: xrtk/com.xrtk.test
          path: test-project

      - uses: xrtk/unity-validate@v2
        with:
          version-file-path: 'test-project/**/ProjectSettings/ProjectVersion.txt'

      - name: activate unity license
        uses: ./
        with:
          editor-path: ${{ env.editor-path }}
          username: ${{ secrets.UNITY_USERNAME }}
          license: ${{ secrets.UNITY_PERSONAL_LICENSE }}
          password: ${{ secrets.UNITY_PASSWORD }}
          serial: ${{ secrets.UNITY_SERIAL }}

      - name: Unity Build (${{ matrix.build-target }})
        uses: xrtk/unity-build@refactored-unity-action-test
        with:
          build-target: ${{ matrix.build-target }}
